version: "3.8"

services:
  frontend:
    image: ishgervais/client_ebilling:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
    links:
      - backend

  backend:
    image: ishgervais/server_ebilling:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - "./backend:/app"

  nginx:
    image: "ishgervais/nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"

volumes:
  frontend:
  backend:
  db:
