name: Docker series CI
on:
  push:
    branches: [exam]
  pull_request:
    branches: [exam]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Runs a single command using the runners shell
      - name: Docker build
        run: |
          docker build ./server -t ishgervais/server_ebilling
          docker build ./client -t ishgervais/client_ebilling
          docker build ./nginx -t ishgervais/nginx
      - name: Docker push
        run: |
          docker push ishgervais/server_ebilling
          docker push ishgervais/client_ebilling
          docker push ishgervais/nginx